### ISSUE TITLE
Does not work for Variation SKUs

### ISSUE THREAD

**Issue by btraas** [varunsridharan/sku-shortlink-for-woocommerce#1]
Product variation SKUs show a 404 page. Is this something that can be added easily?

**Comment by technofreaky** [comment]
@btraas right now its not possible to show variation product using SKU. because a single variation dose not have a single page default by woocommerce. but you can try using 

https://codecanyon.net/item/woocommerce-show-single-variations/13523915

**Comment by btraas** [comment]
@technofreaky is it possible to redirect variation SKU -> product SKU?

**Comment by technofreaky** [comment]
@btraas 

Not sure. but let me check if its possible and update you

**Comment by ScriptProdigy** [comment]
@varunsridharan is this a thing?

I am using iconics plugin for variations but if you have 2 variations with the same attributes (yet the product images are slightly different and the sku is different) it will always redirect to 1 of the 2 variations. Want to use sku's in the variation links to fix this problem, rather than the standard "?attribute_pa_color=yellow&attribute_pa_print-color=rainbow&attribute_pa_weight=173"

Any help is MUCH appreciated
